TEMPLATEROOT = ..

# compilation flags for gdb

CFLAGS  = -O1 -g
ASFLAGS = -g 

# object files

OBJS=  $(STARTUP) main.o  f3d_uart.o f3d_systick.o newlib_stubs.o stm32f30x_usart.o stm32f30x_rcc.o stm32f30x_gpio.o stm32f30x_misc.o queue.o f3d_uart2.o

# include common make file

include $(TEMPLATEROOT)/Makefile.common
