TEMPLATEROOT = ..

# compilation flags for gdb

CFLAGS  = -O1 -g
ASFLAGS = -g 

# object files

OBJS=  $(STARTUP) main.o stm32f30x_rcc.o stm32f30x_usart.o  stm32f30x_gpio.o f3d_led.o f3d_button.o f3d_uart.o

# include common make file

include $(TEMPLATEROOT)/Makefile.common


