TEMPLATEROOT = ..

# compilation flags for gdb

CFLAGS  = -O1 -g
ASFLAGS = -g 

# object files

OBJS=  $(STARTUP) main.o f3d_led.o f3d_uart.o newlib_stubs.o

# include common make file

include $(TEMPLATEROOT)/Makefile.common


